/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MisPastelesRouteImport } from './routes/mis-pasteles'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PastelesIdRouteImport } from './routes/pasteles.$id'
import { Route as PastelesIdIndexRouteImport } from './routes/pasteles.$id.index'
import { Route as AdminPastelesIndexRouteImport } from './routes/admin.pasteles.index'
import { Route as PastelesIdPersonalizarRouteImport } from './routes/pasteles.$id.personalizar'
import { Route as AdminPastelesIdRouteImport } from './routes/admin.pasteles.$id'

const MisPastelesRoute = MisPastelesRouteImport.update({
  id: '/mis-pasteles',
  path: '/mis-pasteles',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastelesIdRoute = PastelesIdRouteImport.update({
  id: '/pasteles/$id',
  path: '/pasteles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PastelesIdIndexRoute = PastelesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PastelesIdRoute,
} as any)
const AdminPastelesIndexRoute = AdminPastelesIndexRouteImport.update({
  id: '/pasteles/',
  path: '/pasteles/',
  getParentRoute: () => AdminRoute,
} as any)
const PastelesIdPersonalizarRoute = PastelesIdPersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => PastelesIdRoute,
} as any)
const AdminPastelesIdRoute = AdminPastelesIdRouteImport.update({
  id: '/pasteles/$id',
  path: '/pasteles/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/mis-pasteles': typeof MisPastelesRoute
  '/pasteles/$id': typeof PastelesIdRouteWithChildren
  '/admin/pasteles/$id': typeof AdminPastelesIdRoute
  '/pasteles/$id/personalizar': typeof PastelesIdPersonalizarRoute
  '/admin/pasteles/': typeof AdminPastelesIndexRoute
  '/pasteles/$id/': typeof PastelesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/mis-pasteles': typeof MisPastelesRoute
  '/admin/pasteles/$id': typeof AdminPastelesIdRoute
  '/pasteles/$id/personalizar': typeof PastelesIdPersonalizarRoute
  '/admin/pasteles': typeof AdminPastelesIndexRoute
  '/pasteles/$id': typeof PastelesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/mis-pasteles': typeof MisPastelesRoute
  '/pasteles/$id': typeof PastelesIdRouteWithChildren
  '/admin/pasteles/$id': typeof AdminPastelesIdRoute
  '/pasteles/$id/personalizar': typeof PastelesIdPersonalizarRoute
  '/admin/pasteles/': typeof AdminPastelesIndexRoute
  '/pasteles/$id/': typeof PastelesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/mis-pasteles'
    | '/pasteles/$id'
    | '/admin/pasteles/$id'
    | '/pasteles/$id/personalizar'
    | '/admin/pasteles/'
    | '/pasteles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/mis-pasteles'
    | '/admin/pasteles/$id'
    | '/pasteles/$id/personalizar'
    | '/admin/pasteles'
    | '/pasteles/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/carrito'
    | '/mis-pasteles'
    | '/pasteles/$id'
    | '/admin/pasteles/$id'
    | '/pasteles/$id/personalizar'
    | '/admin/pasteles/'
    | '/pasteles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarritoRoute: typeof CarritoRoute
  MisPastelesRoute: typeof MisPastelesRoute
  PastelesIdRoute: typeof PastelesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mis-pasteles': {
      id: '/mis-pasteles'
      path: '/mis-pasteles'
      fullPath: '/mis-pasteles'
      preLoaderRoute: typeof MisPastelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasteles/$id': {
      id: '/pasteles/$id'
      path: '/pasteles/$id'
      fullPath: '/pasteles/$id'
      preLoaderRoute: typeof PastelesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasteles/$id/': {
      id: '/pasteles/$id/'
      path: '/'
      fullPath: '/pasteles/$id/'
      preLoaderRoute: typeof PastelesIdIndexRouteImport
      parentRoute: typeof PastelesIdRoute
    }
    '/admin/pasteles/': {
      id: '/admin/pasteles/'
      path: '/pasteles'
      fullPath: '/admin/pasteles/'
      preLoaderRoute: typeof AdminPastelesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pasteles/$id/personalizar': {
      id: '/pasteles/$id/personalizar'
      path: '/personalizar'
      fullPath: '/pasteles/$id/personalizar'
      preLoaderRoute: typeof PastelesIdPersonalizarRouteImport
      parentRoute: typeof PastelesIdRoute
    }
    '/admin/pasteles/$id': {
      id: '/admin/pasteles/$id'
      path: '/pasteles/$id'
      fullPath: '/admin/pasteles/$id'
      preLoaderRoute: typeof AdminPastelesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPastelesIdRoute: typeof AdminPastelesIdRoute
  AdminPastelesIndexRoute: typeof AdminPastelesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPastelesIdRoute: AdminPastelesIdRoute,
  AdminPastelesIndexRoute: AdminPastelesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PastelesIdRouteChildren {
  PastelesIdPersonalizarRoute: typeof PastelesIdPersonalizarRoute
  PastelesIdIndexRoute: typeof PastelesIdIndexRoute
}

const PastelesIdRouteChildren: PastelesIdRouteChildren = {
  PastelesIdPersonalizarRoute: PastelesIdPersonalizarRoute,
  PastelesIdIndexRoute: PastelesIdIndexRoute,
}

const PastelesIdRouteWithChildren = PastelesIdRoute._addFileChildren(
  PastelesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CarritoRoute: CarritoRoute,
  MisPastelesRoute: MisPastelesRoute,
  PastelesIdRoute: PastelesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
