/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MisPastelesRouteImport } from './routes/mis-pasteles'
import { Route as AdminPastelesIndexRouteImport } from './routes/admin.pasteles.index'
import { Route as AdminPastelesIdRouteImport } from './routes/admin.pasteles.$id'
import { Route as IndexRouteImport } from './routes/index'

const MisPastelesRoute = MisPastelesRouteImport.update({
  id: '/mis-pasteles',
  path: '/mis-pasteles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPastelesIndexRoute = AdminPastelesIndexRouteImport.update({
  id: '/admin/pasteles/',
  path: '/admin/pasteles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPastelesIdRoute = AdminPastelesIdRouteImport.update({
  id: '/admin/pasteles/$id',
  path: '/admin/pasteles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mis-pasteles': typeof MisPastelesRoute
  '/admin/pasteles': typeof AdminPastelesIndexRoute
  '/admin/pasteles/$id': typeof AdminPastelesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mis-pasteles': typeof MisPastelesRoute
  '/admin/pasteles': typeof AdminPastelesIndexRoute
  '/admin/pasteles/$id': typeof AdminPastelesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mis-pasteles': typeof MisPastelesRoute
  '/admin/pasteles/': typeof AdminPastelesIndexRoute
  '/admin/pasteles/$id': typeof AdminPastelesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mis-pasteles' | '/admin/pasteles' | '/admin/pasteles/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mis-pasteles' | '/admin/pasteles' | '/admin/pasteles/$id'
  id: '__root__' | '/' | '/mis-pasteles' | '/admin/pasteles/' | '/admin/pasteles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MisPastelesRoute: typeof MisPastelesRoute
  AdminPastelesIndexRoute: typeof AdminPastelesIndexRoute
  AdminPastelesIdRoute: typeof AdminPastelesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mis-pasteles': {
      id: '/mis-pasteles'
      path: '/mis-pasteles'
      fullPath: '/mis-pasteles'
      preLoaderRoute: typeof MisPastelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pasteles/': {
      id: '/admin/pasteles/'
      path: '/admin/pasteles'
      fullPath: '/admin/pasteles'
      preLoaderRoute: typeof AdminPastelesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pasteles/$id': {
      id: '/admin/pasteles/$id'
      path: '/admin/pasteles/$id'
      fullPath: '/admin/pasteles/$id'
      preLoaderRoute: typeof AdminPastelesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MisPastelesRoute: MisPastelesRoute,
  AdminPastelesIndexRoute: AdminPastelesIndexRoute,
  AdminPastelesIdRoute: AdminPastelesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
